services:
  - type: web
    name: influencer-search-api
    plan: free  # Explicitly specify free tier
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: GEMINI_API_KEY
        value: your_api_key_here
      - key: PORT
        value: 8000
    healthCheckPath: /health
